version: '3.3'

services:
  database:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=venera
      - POSTGRES_DATABASE\venera
      - POSTGRES_PASSWORD=qweasd123

  venera:
    build: .
    container_name: venera
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/etc/venera
